var x = 10;
var y = 20;
console.log(x + y);
console.log(x == y);
console.log(x / y);
console.log(x % y);
console.log(y - x);
console.log(x * y);
x++;
console.log(x + y);
y--;
console.log(y);
console.log("***************");
console.log(x -= y);
console.log(x += y);
console.log(x /= y);
console.log(x *= y);
console.log("***************");
console.log(x > y);
console.log(x < y);
console.log(x != y);
console.log(x > y ? x : y);
console.log(x < y ? x : y);
